/*
 * Copyright 2018-2021 Crown Copyright
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

package uk.gov.gchq.syntheticdatagenerator.types;

import java.util.Random;

/**
 * @brief Lista de varios hospitales de España
 */
public enum BirthLocationName {
    HOSPITAL_UNIVERSITARIO_LA_PAZ_10000,
    HOSPITAL_CLINIC_I_PROVINCIAL_DE_BARCELONA_8726,
    HOSPITAL_GENERAL_UNIVERSITARIO_GREGORIO_MARANHON_8322,
    HOSPITAL_UNIVERSITARIO_12_DE_OCTUBRE_7883,
    HOSPITAL_UNIVERSITARI_VALL_DHEBRON_7820,
    HOSPITAL_UNIVERSITARI_I_POLITECNIC_LA_FE_7112,
    HOSPITAL_UNIVERSITARIO_RAMON_Y_CAJAL_6724,
    HOSPITAL_UNIVERSITARIO_FUNDACION_JIMENEZ_DIAZ_6191,
    HOSPITAL_UNIVERSITARIO_VIRGEN_DEL_ROCIO_5728,
    HOSPITAL_UNIVERSITARIO_PUERTA_DE_HIERRO_MAJADAHONDA_5664,
    HOSPITAL_CLINICO_SAN_CARLOS_5530,
    HOSPITAL_UNIVERSITARIO_VIRGEN_MACARENA_5104,
    HOSPITAL_CLINICO_UNIVERSITARIO_VIRGEN_DE_LA_ARRIXACA_5028,
    HOSPITAL_REGIONAL_UNIVERSITARIO_DE_MALAGA_5015,
    HOSPITAL_UNIVERSITARIO_REINA_SOFIA_DE_CORDOBA_4974,
    HOSPITAL_UNIVERSITARI_DE_BELLVITGE_4967,
    HOSPITAL_DE_LA_SANTA_CREU_I_SANT_PAU_4955,
    COMPLEJO_HOSPITALARIO_UNIVERSITARIO_DE_A_CORUNHA_4937,
    HOSPITAL_UNIVERSITARIO_CENTRAL_DE_ASTURIAS_4779,
    COMPLEJO_ASISTENCIAL_UNIVERSITARIO_SALAMANCA_4773,
    HOSPITAL_UNIVERSITARIO_DE_LA_PRINCESA_4766,
    HOSPITAL_CLINICO_UNIVERSITARIO_DE_VALENCIA_4744,
    HOSPITAL_UNIVERSITARIO_DOCTOR_PESET_4733,
    HOSPITAL_UNIVERSITARIO_MARQUES_DE_VALDECILLA_4709,
    HOSPITAL_DEL_MAR_4636,
    HOSPITAL_UNIVERSITARIO_RIO_HORTEGA_4622,
    HOSPITAL_UNIVERSITARIO_REY_JUAN_CARLOS_DE_MOSTOLES_4465,
    HOSPITAL_UNIVERSITARIO_NTRA_SRA_DE_CANDELARIA_4462,
    HOSPITAL_GALDAKAO_USANSOLO_4456,
    HOSPITAL_UNIVERSITARIO_VIRGEN_DE_LAS_NIEVES_4448;

    public static BirthLocationName generate(final Random random) {
        return BirthLocationName.values()[random.nextInt(BirthLocationName.values().length)];
    }
}


